parameters:
    ef.contact.min_submit_delay_seconds: 3
    ef.contact.recaptcha_min_score: 0.5
    ef.contact.whatsapp_default: ''
    ef.contact.whatsapp: '%env(default:ef.contact.whatsapp_default:CONTACT_WHATSAPP)%'
    ef.moderation_contact: '%env(MODERATION_CONTACT)%'
    ef.contact.recipient: '%env(CONTACT_RECIPIENT)%'
